# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
include: package:lints/recommended.yaml

analyzer:
  # You can exclude files from analysis
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - ".dart_tool/**"

  # Stronger lints for a CLI tool
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    # Promote warnings to errors
    missing_required_param: error
    missing_return: error
    unused_element: warning
    unused_import: warning
    unused_local_variable: warning

linter:
  rules:
    # Errors - these will fail the build
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_unused_constructor_parameters: true
    camel_case_types: true
    constant_identifier_names: true
    empty_catches: true
    empty_statements: true
    file_names: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    non_constant_identifier_names: false  # We use templates, so disable this
    one_member_abstracts: true
    overridden_fields: true
    package_names: true
    package_prefixed_library_names: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: false  # CLI generates code, so allow non-final
    prefer_for_elements_to_map_fromIterable: true
    prefer_generic_function_type_aliases: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_null_aware_operators: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    recursive_getters: true
    slash_for_doc_comments: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    type_init_formals: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_full_hex_values_for_flutter_colors: false  # Not a Flutter app
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    valid_regexps: true
    void_checks: true

    # Disable Flutter-specific rules
    avoid_print: false  # CLI tools need to print
    avoid_slow_async_io: false  # CLI does file I/O
    avoid_web_libraries_in_flutter: false  # Not Flutter
    flutter_style_todos: false  # Not Flutter
    prefer_const_constructors_in_immutables: false  # Not Flutter
    prefer_double_quotes: false  # Single quotes are fine for CLI
    require_trailing_commas: false  # Optional for CLI