import 'package:embit_cli/src/models/feature_config.dart';

class DITemplates {
  // Core DI Container
  static String appDIContainer(String projectPath, List<String> features) => '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is automatically generated by Embit CLI

import 'package:get_it/get_it.dart';
import 'package:${projectPath}/core/network/network_info.dart';
import 'package:${projectPath}/core/database/local_database.dart';

${features.map((f) => "import 'package:${projectPath}/features/$f/di/${f}_di.dart';").join('\n')}

final GetIt getIt = GetIt.instance;

Future<void> initDependencyInjection() async {
  // Core dependencies
  getIt.registerLazySingleton<NetworkInfo>(
    () => NetworkInfoImpl(),
  );
  
  getIt.registerLazySingleton<LocalDatabase>(
    () => LocalDatabaseImpl(),
  );
  
  // Feature registrations
${features.map((f) => '  register${_toPascalCase(f)}Feature();').join('\n')}
}

String _toPascalCase(String input) {
  return input.split('_').map((word) {
    if (word.isEmpty) return '';
    return '\${word[0].toUpperCase()}\${word.substring(1)}';
  }).join();
}
''';

  // Route aggregator
  static String routeAggregator(String projectPath, List<String> features) => '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is automatically generated by Embit CLI

import 'package:flutter/material.dart';
${features.map((f) => "import 'package:${projectPath}/features/$f/routes/${f}_routes.dart';").join('\n')}

Map<String, WidgetBuilder> getAllRoutes() {
  final routes = <String, WidgetBuilder>{};
  
${features.map((f) => '  routes.addAll(get${_toPascalCase(f)}Routes());').join('\n')}
  
  return routes;
}

class AppRouter {
  static Route<dynamic> generateRoute(RouteSettings settings) {
    final routes = getAllRoutes();
    
    final builder = routes[settings.name];
    if (builder != null) {
      return MaterialPageRoute(
        builder: builder,
        settings: settings,
      );
    }
    
    return MaterialPageRoute(
      builder: (_) => Scaffold(
        body: Center(
          child: Text('No route defined for \${settings.name}'),
        ),
      ),
    );
  }
}

String _toPascalCase(String input) {
  return input.split('_').map((word) {
    if (word.isEmpty) return '';
    return '\${word[0].toUpperCase()}\${word.substring(1)}';
  }).join();
}
''';

  // Feature registry
  static String featureRegistry(List<String> features) => '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is automatically generated by Embit CLI

abstract class FeatureInfo {
  String get name;
  String get route;
  String get displayName;
}

final List<FeatureInfo> registeredFeatures = [
${features.map((f) => '  ${_toPascalCase(f)}FeatureInfo(),').join('\n')}
];

${features.map((f) => _featureInfoClass(f)).join('\n')}
''';

  static String _featureInfoClass(String featureName) {
    final pascal = _toPascalCase(featureName);
    return '''
class ${pascal}FeatureInfo implements FeatureInfo {
  @override
  String get name => '$featureName';
  
  @override
  String get route => '/$featureName';
  
  @override
  String get displayName => '$pascal';
}
''';
  }

  static String _toPascalCase(String input) {
    return input.split('_').map((word) {
      if (word.isEmpty) return '';
      return '${word[0].toUpperCase()}${word.substring(1)}';
    }).join();
  }
}